### PR TITLE
Initialise alt with type specific 0 instead of Float64

### PR DESCRIPTION
**Pull request by lwabeke**
Without this change constructors using Float32 variables fail.

### CODE REVIEW

**Comment by lwabeke** [comment]
The keyword constructor is still a problem:
LLA(;lat=NaN,lon=NaN,alt=0.0)
But not sure how to fix this.

**Comment by lwabeke** [comment]
Quick attempt to try to address
 https://github.com/JuliaGeo/Geodesy.jl/issues/29

**Comment by andyferris** [comment]
Thanks @lwabeke - looks good.

Keyword constructors are currently not type-stable (meaning, in general in Julia, unless they have a fully-defined type like `alt::Float64 = 0.0`, but this of course doesn't fix your problem) so I'm not worried about this. Have you tried `alt = zero(lon)`, as default values can usually depend on earlier ones (but I'm not as certain about keyword arguments).

**Comment by lwabeke** [comment]
The problem in that keyword constructor is that NaN if already Float64, thus unless all 3 are specified as being a different type, it will cause problems. But I'm also not too worried about that case.

**Comment by c42f** [comment]
Eek, we should have merged this ages ago, thanks for the patch.

**Pull request merged**
