### PR TITLE
Migrate to Julia 0.7 and 1.0 compatibility

### PR DESCRIPTION
**Pull request by garborg**

### CODE REVIEW

**Comment by garborg** [comment]
I left the custom atan2d implementation's name unchanged because it seemed less confusing to me (knowing whether calling base's version or not and we call one-arg methods of atand as well in the code).

Seems like a straightforward PR, so I'll merge it in a day or two if @c42f and @andyferris are busy elsewhere.

**Comment by visr** [comment]
Great, thanks! Looks like you still need to update CI, removing 0.6, adding 1.0. For Travis to work it needs a `using Pkg;` prefix, and for AppVeyor you can use the format of https://github.com/JuliaCI/Appveyor.jl now.

**Comment by garborg** [comment]
Thanks, will try those changes when at home.

Sent from my phone

On Aug 21, 2018, at 8:04 AM, Martijn Visser <notifications@github.com>
wrote:

Great, thanks! Looks like you still need to update CI, removing 0.6, adding
1.0. For Travis to work it needs a using Pkg; prefix, and for AppVeyor you
can use the format of https://github.com/JuliaCI/Appveyor.jl now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JuliaGeo/Geodesy.jl/pull/44#issuecomment-414666229>,
or mute
the thread

**Comment by andyferris** [comment]
Thanks :)

Let’s fix the CI and then merge and tag. Exciting days!

**Comment by garborg** [comment]
Not sure why the mac build hung for julia 1 on travis, but it passed everywhere it didn't hang. I assume this is a common travis/julia issue these days and we're good to go, but I'll leave it to someone who's been around recently.

**Comment by visr** [comment]
Restarted the hanging one, now it works :)

**Comment by garborg** [comment]
Cool!

**Pull request merged**
