### PR TITLE
Upgrade to new CoordinateTransformations interface

### PR DESCRIPTION
**Pull request by andyferris**
```
AbstractTransformation{InT,OutT} -> Transformation
transform(tform, x) -> tform(x)
```

### CODE REVIEW

**Comment by c42f** [comment]
Looks great.  I see you snuck in some `transform_deriv` methods - how about some tests?

**Comment by andyferris** [comment]
Those made it in by accident, actually (rookie git mistake)...

**Comment by visr** [comment]
Note the failing tests. I guess it is because a new version of CoordinateTransformations.jl needs to be tagged?

**Comment by c42f** [comment]
@visr yes, both these packages are in a mutual state of flux since they're rather interdependent while some of the basic API stuff is being sorted out.  We figured we'd do a synchronized update to metadata, making sure CoordinateTransformations gets in there first.

**Pull request merged**
